import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
 title: "Weather Waffle",
 description: "Generated by create next app", //need to come up a w good description for SEO
};

export default function RootLayout({ children }) {
 return (
  <html lang="en">
   <link
    rel="icon"
    href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🧇</text></svg>"
   />
   <body className={inter.className}>
    <Header />
    {children}
    <Footer />
   </body>
  </html>
 );
}
